#!/bin/bash
git -C ~/python/ fetch && git -C ~/python/ reset --hard origin/main 
tmux new-session -ds logs
tmux split-window -t logs
tmux split-window -t logs
tmux split-window -t logs
tmux send-keys -t logs.0 "uv run --directory ~/python/ tftbot.py" ENTER
tmux send-keys -t logs.1 "uv run --directory ~/python/ watcher.py" ENTER
tmux send-keys -t logs.2 "uv run --directory ~/python/ meeseeks.py" ENTER
tmux send-keys -t logs.3 "tail -f ~/logs/ash_nazg.log | grep -ve \"\[DEBUG\]\"" ENTER
tmux select-pane -T tftbot -t logs.0
tmux select-pane -T watcher -t logs.1
tmux select-pane -T mrmeeseeks -t logs.2
tmux select-pane -T watchlist -t logs.3
tmux select-layout -t logs even-vertical
tmux new-window -n misc
